### PR TITLE
Implement Daily Schedule List

### LINKED ISSUE #96: GUI Improvements
As a novice user, I want to be able to see my schedule sorted by days so that I am able to plan for my meetings more efficiently

### PR DESCRIPTION
**Pull request by jewiteo**
closes #96

### CODE REVIEW

**Comment by LimKaiWei** [comment]
Should the behaviour of `see d/23-10-2024` show events from 20-10-2024 to 26-10-2024 or 21-10-2024 to 27-10-2024?

**Comment by tata32000** [comment]
> Should the behaviour of `see d/23-10-2024` show events from 20-10-2024 to 26-10-2024 or 21-10-2024 to 27-10-2024?

Depends if you want to start from Sunday or Monday right? Personally I think Monday makes abit more sense as it seems to more popular.

image

Reference: https://ux.stackexchange.com/questions/45771/what-day-should-a-calendar-start-on-and-does-it-matter

**Comment by LimKaiWei** [comment]
<details><summary>Replies</summary>
<p>

> > Should the behaviour of `see d/23-10-2024` show events from 20-10-2024 to 26-10-2024 or 21-10-2024 to 27-10-2024?
> 
> Depends if you want to start from Sunday or Monday right? Personally I think Monday makes abit more sense as it seems to more popular.
> 
> image
> 
> Reference: https://ux.stackexchange.com/questions/45771/what-day-should-a-calendar-start-on-and-does-it-matter


</p>
</details> 

Possible to make choice of moday/sunday start of week into a user pref? not critical as of now but just a thought

**Review by LimKaiWei — APPROVED** [review]
LGTM otherwise

**Pull request merged**
